-- Supabase SQL Editor에 복사해서 실행해주세요.
-- 데이터베이스 테이블(HansollAIGallery) 생성 쿼리

CREATE TABLE public."HansollAIGallery" (
    id bigint generated by default as identity primary key,
    "Title" text,
    "Reason" text,
    "HowToUse" text,
    "KeyWord" text,
    "PassWord" text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS (Row Level Security) 활성화
ALTER TABLE public."HansollAIGallery" ENABLE ROW LEVEL SECURITY;

-- (선택) 누구나 테이블의 데이터를 읽고 쓸 수 있도록 정책 추가
-- 필요에 따라 보안 정책을 수정해주세요.
CREATE POLICY "Enable read access for all users" ON public."HansollAIGallery" FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public."HansollAIGallery" FOR INSERT WITH CHECK (true);
