-- ==============================================================================
-- [AI Gallery - System Info] 자료 공유/아카이브 전용 Supabase 테이블 스키마
-- 테이블명: archive
-- ==============================================================================
-- ★ [기존 archive 테이블에 직급 코드(occp_grd_cd)와 직급 명(occp_grd_nm) 필드 추가 시 실행]
-- ALTER TABLE public.archive ADD COLUMN IF NOT EXISTS occp_grd_cd TEXT NOT NULL DEFAULT '';
-- ALTER TABLE public.archive ADD COLUMN IF NOT EXISTS occp_grd_nm TEXT NOT NULL DEFAULT '';
-- COMMENT ON COLUMN public.archive.occp_grd_cd IS '작성자 직급코드';
-- COMMENT ON COLUMN public.archive.occp_grd_nm IS '작성자 직급명';
-- ==============================================================================

-- 1. 기존 테이블이 있다면 삭제 (필요 시 주석 해제)
-- DROP TABLE IF EXISTS public.archive;

-- 2. archive 테이블 생성
CREATE TABLE IF NOT EXISTS public.archive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 고유 기본키
    cd_dept TEXT NOT NULL DEFAULT '',                       -- 부서코드 (예: 'IT', 'BIZ3')
    nm_dept TEXT NOT NULL DEFAULT '',                       -- 부서명 (예: 'IT부', '사업 3부')
    emp_no TEXT NOT NULL DEFAULT '',                        -- 작성자 사번 (예: '20240001')
    emp_nm TEXT NOT NULL DEFAULT '',                        -- 작성자 성명 (예: '윤지훈')
    occp_grd_cd TEXT NOT NULL DEFAULT '',                   -- 직급코드 (예: 'J2', 'M1')
    occp_grd_nm TEXT NOT NULL DEFAULT '',                   -- 직급명 (예: '책임', '선임')
    category TEXT NOT NULL DEFAULT '기술 가이드',             -- 카테고리 ('기술 가이드', '참고 문서', '기타')
    title TEXT NOT NULL DEFAULT '',                         -- 자료 제목
    contents TEXT NOT NULL DEFAULT '',                      -- 자료 설명 및 본문 내용
    files JSONB DEFAULT '[]'::jsonb,                        -- 첨부파일 배열 [{"name": "...", "path": "...", "size": "..."}]
    links JSONB DEFAULT '[]'::jsonb,                        -- 참고 URL 배열 [{"title": "...", "url": "..."}]
    password TEXT NOT NULL DEFAULT '1234',                  -- 수정·삭제 검증용 4자리 비밀번호
    views INTEGER NOT NULL DEFAULT 0,                       -- 조회수
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),          -- 최초 등록일시
    updated_at TIMESTAMPTZ DEFAULT NOW()                    -- 최종 수정일시
);

-- 3. 테이블 코멘트 및 컬럼 설명 추가
COMMENT ON TABLE public.archive IS 'AI Gallery System Info - 자료 공유 및 아카이브 게시판 테이블';
COMMENT ON COLUMN public.archive.id IS '고유 기본키 (ID)';
COMMENT ON COLUMN public.archive.cd_dept IS '작성자 부서코드';
COMMENT ON COLUMN public.archive.nm_dept IS '작성자 부서명';
COMMENT ON COLUMN public.archive.emp_no IS '작성자 사번';
COMMENT ON COLUMN public.archive.emp_nm IS '작성자 성명';
COMMENT ON COLUMN public.archive.occp_grd_cd IS '작성자 직급코드';
COMMENT ON COLUMN public.archive.occp_grd_nm IS '작성자 직급명';
COMMENT ON COLUMN public.archive.category IS '카테고리 (기술 가이드, 참고 문서, 기타)';
COMMENT ON COLUMN public.archive.title IS '자료 제목';
COMMENT ON COLUMN public.archive.contents IS '자료 설명 및 내용';
COMMENT ON COLUMN public.archive.files IS '첨부파일 정보 JSONB 배열';
COMMENT ON COLUMN public.archive.links IS '참고 URL 링크 JSONB 배열';
COMMENT ON COLUMN public.archive.password IS '수정·삭제용 비밀번호';
COMMENT ON COLUMN public.archive.views IS '조회수';
COMMENT ON COLUMN public.archive.created_at IS '최초 등록 일시';
COMMENT ON COLUMN public.archive.updated_at IS '최종 수정 일시';

-- 4. RLS (Row Level Security) 설정
ALTER TABLE public.archive ENABLE ROW LEVEL SECURITY;

-- 5. 모든 사용자 조회/생성/수정/삭제 허용 정책 (사내 인트라넷 환경 기준)
CREATE POLICY "Allow All Access on archive"
ON public.archive
FOR ALL
USING (true)
WITH CHECK (true);

-- 6. updated_at 자동 갱신 트리거 (선택 사항)
CREATE OR REPLACE FUNCTION update_archive_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE OR REPLACE TRIGGER update_archive_updated_at
    BEFORE UPDATE ON public.archive
    FOR EACH ROW
    EXECUTE FUNCTION update_archive_updated_at_column();
