const { Client } = require('pg');

const connectionString = 'postgresql://postgres.yvklsrhmcbdanswxysrw:swjdghWkd79~!@aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres';

const client = new Client({
  connectionString,
});

async function createTable() {
  try {
    await client.connect();
    console.log('Connected to Supabase Database!');

    const createTableQuery = `
      CREATE TABLE IF NOT EXISTS public."HansollAIGallery" (
          id bigint generated by default as identity primary key,
          "Title" text,
          "Reason" text,
          "HowToUse" text,
          "KeyWord" text,
          "PassWord" text,
          created_at timestamp with time zone default timezone('utc'::text, now()) not null
      );
    `;

    console.log('Creating table...');
    await client.query(createTableQuery);
    console.log('Table "HansollAIGallery" created successfully (or already exists).');

    const enableRlsQuery = `
      ALTER TABLE public."HansollAIGallery" ENABLE ROW LEVEL SECURITY;
    `;
    await client.query(enableRlsQuery);
    console.log('RLS enabled.');

    // RLS Policies
    const checkPolicyQuery = `
      SELECT policyname 
      FROM pg_policies 
      WHERE tablename = 'HansollAIGallery' AND policyname = 'Enable read access for all users';
    `;
    const res1 = await client.query(checkPolicyQuery);
    if (res1.rows.length === 0) {
      await client.query(`CREATE POLICY "Enable read access for all users" ON public."HansollAIGallery" FOR SELECT USING (true);`);
      console.log('Select policy created.');
    }

    const checkPolicyInsertQuery = `
      SELECT policyname 
      FROM pg_policies 
      WHERE tablename = 'HansollAIGallery' AND policyname = 'Enable insert access for all users';
    `;
    const res2 = await client.query(checkPolicyInsertQuery);
    if (res2.rows.length === 0) {
      await client.query(`CREATE POLICY "Enable insert access for all users" ON public."HansollAIGallery" FOR INSERT WITH CHECK (true);`);
      console.log('Insert policy created.');
    }

  } catch (err) {
    console.error('Error executing query:', err);
  } finally {
    await client.end();
  }
}

createTable();
